Algoritmo "ex.002"
// 
//  
// Descrição   : Ler o nome e a idade de um usuário e escreve uma msg na tela
// Autor(a)    : Klerysson Gois
// Data atual  : 30/10/2025
Var
   nome: caractere
   idade: inteiro


Inicio
      escreva("Digite o seu nome: ")
      leia(nome)
      escreva("Informe sua idade: ")
      leia(idade)

      escreva("Seu nome é, ", nome, ", e sua idade é ", idade, " anos")


Fimalgoritmo