Algoritmo "ex.001"
// 
//  
// Descrição   : Realiza a interação com o usuário solicitando o nome e dando boas vindas
// Autor(a)    : Klerysson Gois
// Data atual  : 30/10/2025
Var
   nome: caractere


Inicio
      // Aparece na tela a msg para o usuário digitar o nome
   escreva("Digite o seu nome: ")
   //Armazena o nome do usuário
   leia(nome)
   //Envia uma msg de boas vindas para o usuário
   escreval("Olá, ", nome, ", seja muito bem vindo ao seu curso de algoritmo")
   

Fimalgoritmo